source 'https://rubygems.org'

gem 'rails', '4.1.8'

gem 'bson_ext'
gem 'cancan'
gem 'capistrano-rails', 		group: :development
gem 'carrierwave-mongoid', :require => 'carrierwave/mongoid'
gem 'country_select'
gem 'devise'
gem 'devise-i18n-views',    '~> 0.2'
gem 'faker'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'less-rails'
gem 'meta-tags'
gem 'mini_magick'
gem 'mongo'
gem 'mongoid', '~> 4.0.0.rc1', 	github: 'mongoid/mongoid'
gem 'mongoid-grid_fs', github: 'ahoward/mongoid-grid_fs'
gem 'mongoid_slug'
gem 'rails-i18n', '~> 4.0.0'
gem 'sass-rails', '~> 4.0.3'
gem 'simple_form',          '~> 3.0.1'
gem 'slim'
gem 'spring',        			group: :development
gem 'therubyracer'
gem 'turbolinks'
gem 'twitter-bootstrap-rails'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn'
gem 'will_paginate-bootstrap'
gem 'will_paginate_mongoid'
