    admin = User.create!( birthdate:              '1993-12-10',
                          country_code:           'France',
                          email:                  'admin@epnet.fr',
                          firstname:              'admin',
                          lastname:               'nimda',
                          password:               'adminadmin',
                          password_confirmation:  'adminadmin',
                          phone:                  '0606060606',
                          street:                 '4, rue Jules Guesdes',
                          town:                   'Lille',
                          type:                   'Users::Admin',
                          created_at:             1.week.ago,
                          updated_at:             1.week.ago)